### ISSUE TITLE
SQLite locks when messages are sent concurrently

### ISSUE THREAD

**Issue by selfbc** [AsamK/signal-cli#1069]
When messages send concurrently, the database gets locked and everything starts failing.  Is there the possibility of making this thread safe or giving other database options?  Or is there a setting that I'm missing?

`WARN  MessageSendLogStore - Failed to insert into message send log
org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked)
        at org.sqlite.core.DB.newSQLException(DB.java:1135)
        at org.sqlite.core.DB.newSQLException(DB.java:1146)
        at org.sqlite.core.DB.throwex(DB.java:1106)
        at org.sqlite.core.DB.exec(DB.java:198)
        at org.sqlite.SQLiteConnection.setAutoCommit(SQLiteConnection.java:364)
        at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:401)
        at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
        at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.insert(MessageSendLogStore.java:266)
        at org.asamk.signal.manager.storage.sendLog.MessageSendLogStore.insertIfPossible(MessageSendLogStore.java:121)
        at org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:610)
        at org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:92)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:450)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:554)
        at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:179)
        at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:25)
        at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:15)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler$CommandRunnerImpl.handleCommand(SignalJsonRpcDispatcherHandler.java:253)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.parseParamsAndRunCommand(SignalJsonRpcDispatcherHandler.java:364)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.runCommand(SignalJsonRpcDispatcherHandler.java:312)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.handleRequest(SignalJsonRpcDispatcherHandler.java:166)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.lambda$handleConnection$3(SignalJsonRpcDispatcherHandler.java:144)
        at org.asamk.signal.jsonrpc.JsonRpcReader.handleRequest(JsonRpcReader.java:69)
        at org.asamk.signal.jsonrpc.JsonRpcReader.readMessages(JsonRpcReader.java:44)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.handleConnection(SignalJsonRpcDispatcherHandler.java:144)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.handleConnection(SignalJsonRpcDispatcherHandler.java:77)
        at org.asamk.signal.commands.DaemonCommand.lambda$runSocketMultiAccount$4(DaemonCommand.java:247)
        at org.asamk.signal.commands.DaemonCommand.lambda$runSocket$5(DaemonCommand.java:272)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
ERROR SignalJsonRpcDispatcherHandler - Command execution failed
java.lang.RuntimeException: Failed read recipient store
        at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipient(RecipientStore.java:224)
        at org.asamk.signal.manager.storage.recipients.RecipientResolver$RecipientResolverWrapper.resolveRecipient(RecipientResolver.java:32)
        at org.asamk.signal.manager.storage.recipients.RecipientResolver.resolveRecipient(RecipientResolver.java:17)
        at org.asamk.signal.manager.api.SendMessageResult.from(SendMessageResult.java:44)
        at org.asamk.signal.manager.ManagerImpl.toSendMessageResult(ManagerImpl.java:468)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:451)
        at org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:554)
        at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:179)
        at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:25)
        at org.asamk.signal.commands.JsonRpcLocalCommand.handleCommand(JsonRpcLocalCommand.java:15)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler$CommandRunnerImpl.handleCommand(SignalJsonRpcDispatcherHandler.java:253)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.parseParamsAndRunCommand(SignalJsonRpcDispatcherHandler.java:364)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.runCommand(SignalJsonRpcDispatcherHandler.java:312)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.handleRequest(SignalJsonRpcDispatcherHandler.java:166)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.lambda$handleConnection$3(SignalJsonRpcDispatcherHandler.java:144)
        at org.asamk.signal.jsonrpc.JsonRpcReader.handleRequest(JsonRpcReader.java:69)
        at org.asamk.signal.jsonrpc.JsonRpcReader.readMessages(JsonRpcReader.java:44)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.handleConnection(SignalJsonRpcDispatcherHandler.java:144)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.handleConnection(SignalJsonRpcDispatcherHandler.java:77)`

**Comment by AsamK** [comment]
I can't reproduce this. The `SQLITE_BUSY` happens, when the database is currently locked by another transaction.
What commands are you running exactly and how many? Also some more log entries before the exception might be helpful.

**Comment by selfbc** [comment]
signal-cli is running with signal-cli -daemon --no-receive-stdout --ignore-stories --socket /SIGNAL/.signal-cli/socket
It's then being connected to with software written in golang using RPC over the socket for communication.  I've reduced concurrency which is helping, but locks are still happening if a send and a receive happen concurrently.  I'm happy to provide any additional information or logs, please just let me know what you need.

**Comment by selfbc** [comment]
Is it possible to have an option to disable the message send log?  I'm not sure the purpose that it's serving, but it seems to be the main thing causing locking issues for me.  It would be great if I could disable this all together or just write the log to a text file.

**Comment by AsamK** [comment]
The message send log is used to resend messages, in case the receiver fails to decrypt the message for some reason.
An option could be added to disable the send log, another alternative might be to move the send log to a separate database file so it doesn't interfere with other db accesses.

For now I've just pushed a commit to increase the sqlite busy timeout, so sqlite will wait longer before it throws a SQLITE_BUSY exception. (49aaff2bbe1ec6ed6cdbd26200ec806c46b16489)

**Comment by selfbc** [comment]
Thank you!  I've built it with this change and am currently testing.  If it's not too much work, having an option to disable the send log would be awesome as it would probably also speed things up.  I think the send log is great for situations where you need a better guarantee of delivery, but for this use case I'm just firing messages off quickly and checking the delivery receipts.

**Comment by selfbc** [comment]
I can now confirm that the issue still exists, but this greatly helps it.  It's gone from happening once every 5 minutes or so to happening only about once per hour during times of heavy messaging traffic.  I think moving it to a separate database would further help with the issue, but I believe it's only going to go away by either giving an option to not use the send log or by moving it to a more concurrency friendly database engine.

**Comment by AsamK** [comment]
There's now a global flag to disable the send log (207764e0be91aeb9a6c52fa8639a822555f8759a): `----disable-send-log`

**Comment by selfbc** [comment]
Thank you!  I compiled these changes this morning and I haven't seen a crash yet.  I'm slowly increasing concurrency and will let you know if I see any errors.  Thank you again, that was very quick.

**Comment by selfbc** [comment]
I believe it's safe to say that this issue is fixed at this point.  Using the new feature --disable-send-log, I've been unable to trigger this bug in months.  Thank you for your hard work on this one!
