### ISSUE TITLE
SQLite unique contraint error after upgrading to 0.13.0

### ISSUE THREAD

**Issue by cuu508** [AsamK/signal-cli#1465]
After upgrading to 0.13.0, signal-cli systemd service fails to start up with the following exception:

```
Error loading state file for user +####: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE] A UNIQUE constraint failed (UNIQUE constraint failed: recipient2.pni) (RuntimeException)
```

Running the signal-cli command produces a traceback:

```
java.lang.RuntimeException: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE] A UNIQUE constraint failed (UNIQUE constraint failed: recipient2.pni)
	at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$24(SignalAccount.java:1272)
	at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1721)
	at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1268)
	at org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$10(SignalAccount.java:1234)
	at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1721)
	at org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1230)
	at org.asamk.signal.manager.storage.recipients.RecipientTrustedResolver$RecipientTrustedResolverWrapper.resolveSelfRecipientTrusted(RecipientTrustedResolver.java:32)
	at org.asamk.signal.manager.storage.SignalAccount.init(SignalAccount.java:364)
	at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:198)
	at org.asamk.signal.manager.internal.ProvisioningManagerImpl.canRelinkExistingAccount(ProvisioningManagerImpl.java:203)
	at org.asamk.signal.manager.internal.ProvisioningManagerImpl.finishDeviceLink(ProvisioningManagerImpl.java:109)
	at org.asamk.signal.commands.LinkCommand.handleCommand(LinkCommand.java:46)
	at org.asamk.signal.commands.CommandHandler.handleProvisioningCommand(CommandHandler.java:25)
	at org.asamk.signal.App.handleProvisioningCommand(App.java:255)
	at org.asamk.signal.App.handleCommand(App.java:158)
	at org.asamk.signal.App.init(App.java:144)
	at org.asamk.signal.Main.main(Main.java:56)
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE] A UNIQUE constraint failed (UNIQUE constraint failed: recipient2.pni)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.throwex(DB.java:1150)
	at org.sqlite.core.NativeDB._exec_utf8(Native Method)
	at org.sqlite.core.NativeDB._exec(NativeDB.java:97)
	at org.sqlite.jdbc3.JDBC3Statement.lambda$executeLargeUpdate$2(JDBC3Statement.java:135)
	at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
	at org.sqlite.jdbc3.JDBC3Statement.executeLargeUpdate(JDBC3Statement.java:122)
	at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:109)
	at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:119)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
	at org.asamk.signal.manager.storage.AccountDatabase.upgradeDatabase(AccountDatabase.java:522)
	at org.asamk.signal.manager.storage.Database.initDb(Database.java:67)
	at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:35)
	at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:43)
	at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$24(SignalAccount.java:1270)
	... 16 more
```

I was updating 4 separate signal-cli instances – a primary, and three linked devices. There was no issue on the primary, but I got the exact same error when upgrading each linked device. 

As a workaround, one-by-one, I removed the linked device from the primary, created a new empty data directory for it, and linked it with the primary again.

The old linked devices and their data directories had been around for fairly long, looks like I linked them in November 2021, then using signal-cli-0.9.1. 

My environment: Ubuntu 22.04, openjdk-21-jre, and I'm using prebuilt signal-cli from the releases page (`signal-cli-0.13.0.tar.gz`).

**Comment by m-ueberall** [comment]
I see this as well on one machine after upgrading from v0.12.8 to v0.13.0 (Ubuntu 20.04, native binary).

**Comment by AsamK** [comment]
I've pushed a possible fix, can you try if migration works with this build?
https://github.com/AsamK/signal-cli/actions/runs/7971660845

**Comment by cuu508** [comment]
Unfortunately I cannot test it as I've already re-registered the linked devices :-/

**Comment by m-ueberall** [comment]
I can test it and will come back to you.

**Comment by m-ueberall** [comment]
With a native binary re-built from said commit (`signal-cli0131-SNAPSHOT_git-7bc7242f_ubuntu2004_amd64`), I still see
```
Feb 20 12:49:18 desktop01 systemd[1]: Starting Send secure messages to Signal clients...
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]: ERROR MultiAccountManager - Failed to load +49nnnnnnnnnnn: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE] A UNIQUE constraint failed (UNIQUE constraint failed: recipient2.pni) (RuntimeException)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]: java.lang.RuntimeException: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE] A UNIQUE constraint failed (UNIQUE constraint failed: recipient2.pni)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$24(SignalAccount.java:1272)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1721)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1268)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$10(SignalAccount.java:1234)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1721)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1230)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.asamk.signal.manager.storage.recipients.RecipientTrustedResolver$RecipientTrustedResolverWrapper.resolveSelfRecipientTrusted(RecipientTrustedResolver.java:32)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.asamk.signal.manager.storage.SignalAccount.init(SignalAccount.java:364)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:198)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:97)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.asamk.signal.manager.SignalAccountFiles.lambda$initMultiAccountManager$1(SignalAccountFiles.java:69)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at java.base@21.0.2/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at java.base@21.0.2/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at java.base@21.0.2/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at java.base@21.0.2/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at java.base@21.0.2/java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2192)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at java.base@21.0.2/java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2158)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at java.base@21.0.2/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at java.base@21.0.2/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at java.base@21.0.2/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at java.base@21.0.2/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at java.base@21.0.2/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at java.base@21.0.2/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at java.base@21.0.2/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]: Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE] A UNIQUE constraint failed (UNIQUE constraint failed: recipient2.pni)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.sqlite.core.DB.newSQLException(DB.java:1179)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.sqlite.core.DB.newSQLException(DB.java:1190)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.sqlite.core.DB.throwex(DB.java:1150)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.sqlite.core.NativeDB._exec_utf8(Native Method)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.sqlite.core.NativeDB._exec(NativeDB.java:97)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.sqlite.jdbc3.JDBC3Statement.lambda$executeLargeUpdate$2(JDBC3Statement.java:135)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.sqlite.jdbc3.JDBC3Statement.executeLargeUpdate(JDBC3Statement.java:122)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:109)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:119)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.asamk.signal.manager.storage.AccountDatabase.upgradeDatabase(AccountDatabase.java:522)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.asamk.signal.manager.storage.Database.initDb(Database.java:67)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:35)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:43)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$24(SignalAccount.java:1270)
Feb 20 12:49:19 desktop01 signal-cli_ubuntu2004_amd64[2568314]:   ... 25 more
Feb 20 12:49:19 desktop01 systemd[1]: signal-cli.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 20 12:49:19 desktop01 systemd[1]: signal-cli.service: Failed with result 'exit-code'.
Feb 20 12:49:19 desktop01 systemd[1]: Failed to start Send secure messages to Signal clients.
```
(Service uses `ExecStart=/opt/signal-cli/bin/signal-cli_ubuntu2004_amd64 --config /var/lib/signal-cli daemon --system`, which is a symbolic link to the above binary.)

**Comment by AsamK** [comment]
Thanks for testing, I've pushed another commit to fix it.

**Comment by m-ueberall** [comment]
This change (commit `f1e3b5c9`) did the trick for me! :grinning: 
```
# systemctl status signal-cli.service
● signal-cli.service - Send secure messages to Signal clients
     Loaded: loaded (/etc/systemd/system/signal-cli.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/signal-cli.service.d
             └─override.conf
     Active: active (running) since Tue 2024-02-20 17:25:01 CET; 5s ago
   Main PID: 1498602 (signal-cli_ubun)
      Tasks: 101 (limit: 76944)
     Memory: 165.7M
     CGroup: /system.slice/signal-cli.service
             └─1498602 /opt/signal-cli/bin/signal-cli_ubuntu2004_amd64 --config /var/lib/signal-cli daemon --system

Feb 20 17:25:03 desktop01 signal-cli_ubuntu2004_amd64[1498602]:   When: 1708446303085 (2024-02-20T16:25:03.085Z)
Feb 20 17:25:03 desktop01 signal-cli_ubuntu2004_amd64[1498602]:   Is delivery receipt
Feb 20 17:25:03 desktop01 signal-cli_ubuntu2004_amd64[1498602]:   Timestamps:
[…]
# echo "Hello, world ($(date +%Y%m%d)-1, $(hostname -f), ${ARCH}) - äöüß ÄÖÜẞ" | signal-cli_ubuntu2004_amd64 --dbus-system -a "${PHONE}" send --group "${GROUP}" --message-from-stdin
1708446620523
```
